language: dart

dart:
  - dev

dart_task:
  - test: -p vm
  - test: -p chrome

matrix:
  include:
    - script: pub run --enable-experiment=non-nullable test -p vm,chrome
    - dart_task: dartfmt
    - dart_task:
        dartanalyzer: --enable-experiment=non-nullable --fatal-warnings --fatal-infos .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
